services:
  app:
    build: .
    env_file:
      .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  db:
    image: "postgres:18"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mailpit:
    image: axllent/mailpit:v1.31
    environment:
      - TZ=Europe/Warsaw
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit_data:/data


volumes:
  pgdata:
  mailpit_data:
    driver: local
